### PR TITLE
Format logs info

### PR DESCRIPTION
**Pull request by jianzhangbjz**
**Description of the change:**

**Motivation for the change:**
Just format the log output.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by kevinrizza** [comment]
@jianzhangbjz looks like the bugzilla attached to this pr isn't related to the actual fix? The bz in your header references a bug that has already been verified.

Also it seems like this is something that most likely won't be approved for backport the openshift patch maintainers, can you just remove the bugzilla reference so this will still land in master?

**Comment by anik120** [comment]
> @jianzhangbjz looks like the bugzilla attached to this pr isn't related to the actual fix? The bz in your header references a bug that has already been verified.

Also it seems like this is something that most likely won't be approved for backport the openshift patch maintainers, can you just remove the bugzilla reference so this will still land in master?

In that case this won't be backported to 4.6/4.5

**Comment by jianzhangbjz** [comment]
> can you just remove the bugzilla reference so this will still land in master?

@kevinrizza Yes, sure, thanks for your reminder. Removed it.

**Comment by jianzhangbjz** [comment]
@kevinrizza Could you help to cherry-pick it to release-4.6? Thanks!

**Pull request merged**
