### PR TITLE
Update operator-sdk to v0.6.0

### PR DESCRIPTION
**Pull request by kevinrizza**
As part of normal maintenance, update operator-sdk reference to latest
version

Replication steps:
* Installed latest v0.6.0 operator-sdk binary onto local environment
* Ran `operator-sdk print-deps  --as-file` and copied output
* Replaced top portion of gopkg.toml with `print-deps` output
* Ran `dep ensure` from root of operator-marketplace repository to
install dependencies

### CODE REVIEW

**Comment by tkashem** [comment]
The only concern I have is that it's very close to the release and we don't have a comprehensive set of e2e tests yet.

/lgtm

**Comment by kevinrizza** [comment]
> The only concern I have is that it's very close to the release and we don't have a comprehensive set of e2e tests yet.
> 
> /lgtm

@tkashem Yeah I think we agreed we were going to hold out on this one until after 4.1

**Comment by aravindhp** [comment]
@tkashem @kevinrizza yes, we are holding off on this until 4.2.

**Comment by awgreene** [comment]
Version `v0.0.7` was released last week: https://github.com/operator-framework/operator-sdk/releases

**Comment by aravindhp** [comment]
@awgreene we will move to the latest version of the SDK in the 4.2 timeframe.

**Comment by kevinrizza** [comment]
Looks like this PR needs to be updated again since [v0.7.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.7.0) was released the other day.

**Comment by aravindhp** [comment]
We should wait until we start working on 4.2 and update to the latest version of the SDK that's available

**Comment by kevinrizza** [comment]
Closing as obsolete.

**Pull request closed without merging**
