### PR TITLE
Bug 1771277: Implement Structural Schema

### PR DESCRIPTION
**Pull request by awgreene**
oc explain (and kubectl explain) both broken on Kubernetes version 1.16
due to the release of CRD v1. V1 CRDs require a structural schema for oc
explain to work. This commit introduces the required changes to
implement a structural schema.

### CODE REVIEW

**Comment by ecordell** [comment]
Does this bump our minimum version requirements to 1.16?

**Comment by awgreene** [comment]
> Does this bump our minimum version requirements to 1.16?

It does not @ecordell  - is there a reason you thought it might?

**Comment by awgreene** [comment]
> > Does this bump our minimum version requirements to 1.16?
> 
> It does not @ecordell - is there a reason you thought it might?

@ecordell this does break `k explain csc/opsrc` on earlier versions (1.14 for example), but the CRDs are still deployed and usable.

**Comment by kevinrizza** [comment]
> > > Does this bump our minimum version requirements to 1.16?
> > 
> > 
> > It does not @ecordell - is there a reason you thought it might?
> 
> @ecordell this does break `k explain csc/opsrc` on earlier versions (1.14 for example), but the CRDs are still deployed and usable.


@ecordell @awgreene 

Since we don't have a mechanism for versioning marketplace outside the scope of OpenShift version right now, it's the only way we have to deal with this. IMO I think this is okay if we are trying to move away from this project in all cases other than existing openshift versions.

**Comment by awgreene** [comment]
/hold cancel

Properly linked to the Bugzilla.

**Comment by awgreene** [comment]
/retest
>fail [github.com/openshift/origin/test/extended/marketplace/marketplace_utils.go:18]: Unexpected error:
    <*util.ExitError | 0xc0031207e0>: {
        Cmd: "oc --config=/tmp/admin.kubeconfig create -f /tmp/e2e-test-marketplace-n92bx-config.json",
        StdErr: "unable to recognize no matches for kind \"CatalogSourceConfig\" in version \"operators.coreos.com/v1\"",
        ExitError: {
            ProcessState: {
                pid: 4370,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 285995},
                    Stime: {Sec: 0, Usec: 188884},
                    Maxrss: 130704,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 13211,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 1808,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 2050,
                    Nivcsw: 41,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
occurred

**Comment by awgreene** [comment]
/retest

>level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"

**Pull request merged**
