### PR TITLE
[release-4.12] OCPBUGS-5474: Run Default CatalogSource in Restricted mode

### PR DESCRIPTION
**Pull request by awgreene**
Problem: The marketplace operator has a dependency on an old version of the
operator-framework/api project, preventing it from setting newer fields on the
default catalogSources that it creates.

Solution: This PR updates the marketplace operator to use the latest version
of the operator-framework api, which required a kubernetes dependency
bump. These changes are being introduced so the marketplace-operator
is able to apply some of the latest changes introduced to the
catalogSource api.

This PR also updates the operator marketplace to use the new
coordination.k8s.io/leases api for leader election.

### CODE REVIEW

**Comment by awgreene** [comment]
Created this as a manual cherry-pick of https://github.com/operator-framework/operator-marketplace/pull/498 to make sure that it addresses the core issue on a 4.12 cluster.

**Comment by awgreene** [comment]
e2e-gcp-serial failed due to a known disruption test flake.
/override ci/prow/e2e-gcp-serial

**Comment by jianzhangbjz** [comment]
Test passed, details: https://issues.redhat.com/browse/OCPBUGS-5474
/label qe-approved
/cherry-pick approved

**Pull request merged**
