### PR TITLE
OCPBUGS-2223: Update Default CatalogSource Images to 4.12 tag

### PR DESCRIPTION
**Pull request by awgreene**
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>

### CODE REVIEW

**Comment by awgreene** [comment]
Have seen a number of odd CI failures, created #488 to see if it's related to the image changes in this PR.

**Comment by awgreene** [comment]
Based on the test conducted in #488 (which only included a doc change) it seems like this is a CI failing issue.

**Review by bandrade — COMMENTED** [review]
/label qe-approved
```
OLM version: 0.19.0
git commit: 8ce7b8caa40d0d08d435731c542ed148ad739095

oc get catalogsource -n openshift-marketplace -o yaml | grep image       
    image: registry.redhat.io/redhat/certified-operator-index:v4.12
    image: registry.redhat.io/redhat/community-operator-index:v4.12
    image: registry.redhat.io/redhat/redhat-marketplace-index:v4.12
    image: registry.redhat.io/redhat/redhat-operator-index:v4.12

oc get packagemanifest                                                                             
NAME                                               CATALOG               AGE
prometheus-exporter-operator                       Community Operators   21m
k10-kasten-operator                                Certified Operators   21m
hpe-ezmeral-csi-operator                           Certified Operators   21m
microcks                                           Community Operators   21m
egressip-ipam-operator                             Community Operators   21m
xcrypt-operator-rhmp                               Red Hat Marketplace   21m
cisco-hxcsi-operator                               Certified Operators   21m
volume-expander-operator                           Community Operators   21m
open-liberty-certified                             Certified Operators   21m
amq-online                                         Red Hat Operators     21m
cryostat-operator                                  Red Hat Operators     2

[...]
```

**Comment by awgreene** [comment]
Spinning up a cluster to see what's going on.

**Comment by awgreene** [comment]
`AssertionError AssertionError: Timed out retrying after 30000ms: Expected to find element: `.catalog-tile-pf`, but never found it.`

/test e2e-gcp-console-olm

**Comment by awgreene** [comment]
I was able to use cluster bot to spin up a working cluster based on this PR with all catalogSources running, it isn't clear to me why this is failing.

**Comment by awgreene** [comment]
Console integration tests are fixed in https://github.com/openshift/console/pull/12198

**Pull request merged**
