### PR TITLE
[docs] Update docs with new terminology

### PR DESCRIPTION
**Pull request by SamiSousa**
- Update README stating Marketplace is deployed with OKD 4.0
- Fix broken link to marketplace UI in console repo
- Replace `artifact` with `bundle` to match new nomenclature

Addresses #95

### CODE REVIEW

**Comment by kevinrizza** [comment]
Do we maybe want to move all the docs and scripts related to generating and pushing the operator bundle out of this repo and move it to the courier repository?

**Comment by SamiSousa** [comment]
@kevinrizza That's a good point. @awgreene has already added an equivalent script for pushing to quay to the `community-operators` repo. I'll remove the `how-to-push` doc and script. Not sure if I should move the doc to `community-operators` because in the short term only Alex and I will be pushing.

**Comment by aravindhp** [comment]
>Do we maybe want to move all the docs and scripts related to generating and pushing the operator bundle out of this repo and move it to the courier repository?

Yes that is direction we should move towards.

**Comment by SamiSousa** [comment]
Closing since operator-courier handles pushing to quay, docs have been added to both operator-courier and community-operators repo's.

**Pull request closed without merging**
