### PR TITLE
OCPBUGS-14109: Revert default catsrc diff changes

### PR DESCRIPTION
**Pull request by awgreene**

### CODE REVIEW

**Comment by dtfranz** [comment]
Hello @bandrade, would you please review when you have a moment?

**Comment by Xia-Zhao-rh** [comment]
test result : 
```
zhaoxia@xzha-mac ~ % oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.ci.test-2023-06-01-053907-ci-ln-lx42k7k-latest   True        False         61s     Cluster version is 4.12.0-0.ci.test-2023-06-01-053907-ci-ln-lx42k7k-latest

zhaoxia@xzha-mac ~ % oc get catalogsource  -n openshift-marketplace redhat-operators -o jsonpath='{.spec.updateStrategy.registryPoll.interval}'
10m% 

zhaoxia@xzha-mac ~ % oc patch -n openshift-marketplace catalogsource/redhat-operators --type=merge -p '{"spec":{"updateStrategy":{"registryPoll":{"interval":"30m0s"}}}}'
catalogsource.operators.coreos.com/redhat-operators patched

zhaoxia@xzha-mac ~ % oc get catalogsource  -n openshift-marketplace redhat-operators -o jsonpath='{.spec.updateStrategy.registryPoll.interval}'
30m0s
```

**Pull request merged**
