### PR TITLE
Update owners

### PR DESCRIPTION
**Pull request by oceanc80**
Update owners to add new maintainers.

### CODE REVIEW

**Comment by kevinrizza** [comment]
/approve
maybe one more @awgreene ?

**Review by awgreene — APPROVED** [review]
/approve

**Comment by awgreene** [comment]
/lgtm
Kevin already approved

**Comment by joelanford** [comment]
/label bugzilla/valid-bug

Forcibly setting this because this PR is just fixing up the OWNERS file.

**Pull request merged**
