### PR TITLE
Bug 1986139: update defaults to 4.9

### PR DESCRIPTION
**Pull request by kevinrizza**
**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by anik120 — APPROVED** [review]
/lgtm

**Comment by kevinrizza** [comment]
/hold

some of the images aren't built yet

**Comment by timflannagan** [comment]
It looks like we're waiting for all 4.9 tags to be created since the last failed e2e run:

```
openshift-marketplace                              certified-operators-l4q6m                                             0/1     ImagePullBackOff   0          48m   10.131.0.10    ip-10-0-154-19.us-east-2.compute.internal    <none>           <none>
openshift-marketplace                              certified-operators-n2zzn                                             0/1     ImagePullBackOff   0          58m   10.129.2.14    ip-10-0-196-150.us-east-2.compute.internal   <none>           <none>
openshift-marketplace                              community-operators-9t85f                                             0/1     ImagePullBackOff   0          58m   10.129.2.12    ip-10-0-196-150.us-east-2.compute.internal   <none>           <none>
openshift-marketplace                              community-operators-qvdx9                                             0/1     ImagePullBackOff   0          48m   10.131.0.12    ip-10-0-154-19.us-east-2.compute.internal    <none>           <none>
openshift-marketplace                              marketplace-operator-dd77ccdbd-8xq7c                                  1/1     Running            0          61m   10.130.0.20    ip-10-0-179-12.us-east-2.compute.internal    <none>           <none>
openshift-marketplace                              redhat-marketplace-5ln5z                                              0/1     ImagePullBackOff   0          48m   10.131.0.11    ip-10-0-154-19.us-east-2.compute.internal    <none>           <none>
openshift-marketplace                              redhat-marketplace-6v5xr                                              0/1     ImagePullBackOff   0          59m   10.129.2.13    ip-10-0-196-150.us-east-2.compute.internal   <none>           <none>
openshift-marketplace                              redhat-operators-5btrp                                                0/1     ImagePullBackOff   0          47m   10.131.0.13    ip-10-0-154-19.us-east-2.compute.internal    <none>           <none>
openshift-marketplace                              redhat-operators-f8nz5                                                0/1     ImagePullBackOff   0          59m   10.129.2.11    ip-10-0-196-150.us-east-2.compute.internal   <none>           <none>
```

**Comment by yselkowitz** [comment]
Could a revert of #413 be added to this?

**Pull request merged**
