### PR TITLE
Dockerfile: Align OKD and OCP

### PR DESCRIPTION
**Pull request by LorbusChris**
**Description of the change:**

Alignes the FROM directive in both Dockerfiles with one commonly used elsewhere in OpenShift.
This facilitates builds outside of the Prow CI system.

This change also replaces Dockerfile.rhel7 with a symlink to Dockerfile.
The replacement of Dockerfile.rhel7 is a cleanup that'll allow for removal of Dockerfile.rhel7 eventually.

**Motivation for the change:**

This facilitates builds outside of the Prow CI system.
This will allow for cleanup of the build config in Prow (i.e. switch from consuming Dockerfile.rhel7 to Dockerfile)

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by LorbusChris** [comment]
infra woes
/retest

**Comment by LorbusChris** [comment]
CI is complaining about https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com/k8s/ns/origin/imagestreamtags/scos-4.15%3Amachine-os-images missing. I added the image, but I'm not sure how long it'll take for the image to land on the build cluster..

/test okd-scos-e2e-aws

**Comment by LorbusChris** [comment]
progress, the e2e now runs on AWS. I'll give this another try.

/test okd-scos-e2e-aws

**Comment by vrutkovs** [comment]
LGTM

**Comment by LorbusChris** [comment]
Updated with a more descriptive commit message. This should be good to go now.

/assign @anik120

**Review by grokspawn — APPROVED** [review]

**Comment by LorbusChris** [comment]
I'm going to add the label, even though this isn't really critical, but release-4.14 has branched so this won't affect that release.
/label acknowledge-critical-fixes-only

**Pull request merged**
