### PR TITLE
[docs] Remove contributing section from README

### PR DESCRIPTION
**Pull request by aravindhp**
This has been superseded by CONTRIBUTING.md.
Move the CVO override into the deploy folder.

### CODE REVIEW

**Comment by awgreene** [comment]
This looks good to me.

**Comment by aravindhp** [comment]
@tkashem please review so that it is ready to merge when the hold is removed

**Comment by tkashem** [comment]
Question: `Move the CVO override` is not related to the PR header `Remove contributing section from README`. Is it just about cleaning up the README?

/lgtm

**Pull request merged**
