### PR TITLE
Bug 1683422: [csc] Make CLI output less verbose

### LINKED ISSUE #116: CatalogSourceConfig `kubectl` Output Difficult to Read
### Description

Having [seven items in the `additionalPrinterColumns`](https://github.com/operator-framework/operator-marketplace/blob/master/deploy/crds/catalogsourceconfig.crd.yaml#L19) for the `CatalogSourceConfig` CRD makes the rendered output from `kubectl get` difficult to read on even wide terminals (see screenshots). Consider reducing the number of fields being displayed. Changing `spec.packages` from being a comma-separated string to a proper array would likely help as well.

### Screenshots

**Viewing `CatalogSourceConfigs`:**
screenshot_20190225_135813

**Viewing `Pods`:**

screenshot_20190225_135919

### PR DESCRIPTION
**Pull request by anik120**
- Fixes #116
- Removed `TARGETNAMESPACE`, `PACKAGES`, `DISPLAYNAME` and `PUBLISHER` fields from output
- Modified catalogsourceconfig.crd to remove fields from `additionalPrinterColumns`

### CODE REVIEW

**Comment by kevinrizza** [comment]
Also please update the commit message to include what actually changed (i.e. a reference or description of what changed and why).

**Comment by kevinrizza** [comment]
@aravindhp I think since the purpose of those fields isn't purposefully well documented we can remove them. But in general I think that identifiers like a `DisplayName` would be useful to leave. If we revisit the Display Name as something more robust and for something other than just OpenShift ui, we should add it back in.

**Comment by aravindhp** [comment]
Sounds good @kevinrizza 

@anik120 please remove it for now

**Comment by anik120** [comment]
@aravindhp @kevinrizza just to confirm, we also want the `DISPLAYNAME` and `PUBLISHER` fields removed.

**Comment by kevinrizza** [comment]
@anik120 Yes that is correct.

**Comment by anik120** [comment]
@aravindhp @kevinrizza PTAL now.

**Pull request merged**
