### PR TITLE
OCPBUGS-10926: Update default CatalogSource images to 4.13 tag

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
Update default CatalogSource images to 4.13 tag

### CODE REVIEW

**Review by anik120 — APPROVED** [review]
/approve

**Comment by anik120** [comment]
@oceanc80 I see some alerts emanating from the sources: 

```
alert OperatorHubSourceError fired for 2787 seconds with labels: {container="catalog-operator", endpoint="https-metrics", exported_namespace="openshift-marketplace", instance="10.130.0.27:8443", job="catalog-operator-metrics", name="community-operators", namespace="openshift-operator-lifecycle-manager", pod="catalog-operator-648f875695-pjtjm", service="catalog-operator-metrics", severity="warning"} result=reject
Ginkgo exit error 4: exit with code 4}
```

Did you 
a) Pull the images down yourself to make sure they're available 
b) fire up a cluster-bot with your PR to make sure the pods are getting created?

**Comment by anik120** [comment]
> @oceanc80 I see some alerts emanating from the sources:
> 
> ```
> alert OperatorHubSourceError fired for 2787 seconds with labels: {container="catalog-operator", endpoint="https-metrics", exported_namespace="openshift-marketplace", instance="10.130.0.27:8443", job="catalog-operator-metrics", name="community-operators", namespace="openshift-operator-lifecycle-manager", pod="catalog-operator-648f875695-pjtjm", service="catalog-operator-metrics", severity="warning"} result=reject
> Ginkgo exit error 4: exit with code 4}
> ```
> 
> Did you a) Pull the images down yourself to make sure they're available b) fire up a cluster-bot with your PR to make sure the pods are getting created?

The tests are consistently failing on this PR. We should probably do ☝🏽 before we hit anymore retest

**Comment by grokspawn** [comment]
I pulled the images and brought them up locally and they performed fine on bare docker.

**Comment by everettraven** [comment]
Created #513 and #514  to split this into 2 PRs

**Pull request closed without merging**
