### PR TITLE
Bug 1927478: Add catalog source pod spec overrides

### PR DESCRIPTION
**Pull request by perdasilva**
Signed-off-by: perdasilva <perdasilva@redhat.com>

**Description of the change:**
Updates the catalog source definitions to use the new `grpcPodConfig` to override tolerations, node-selector and priorityClassName.

**Motivation for the change:**
https://bugzilla.redhat.com/show_bug.cgi?id=1927478

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by awgreene — CHANGES_REQUESTED** [review]
I am ready to `lgtm` this, but I would like to clarify one thing before I do so.

We have added these tolerations to the default catalogSource manifests, which users will not be able to override, is this expected behavior?

**Comment by awgreene** [comment]
> I am ready to `lgtm` this, but I would like to clarify one thing before I do so.
> 
> We have added these tolerations to the default catalogSource manifests, which users will not be able to override, is this expected behavior?

I suppose a user could disable these catalogs and then recreate them with their own tolerations.

**Comment by anik120** [comment]
/hold cancel 

/lgtm 
looks all good now :) 

> I suppose a user could disable these catalogs and then recreate them with their own tolerations.

I can confirm that this is true.

**Pull request merged**
