### PR TITLE
Clean up deploy folder

### PR DESCRIPTION
**Pull request by kevinrizza**
-Create new subdirectory called examples
-Move example OperatorSource and CatalogSource to folder

### CODE REVIEW

**Comment by awgreene** [comment]
LGTM

**Comment by SamiSousa** [comment]
Looks good to me

**Comment by awgreene** [comment]
@tkashem `kubectl apply` is not recursive by default.
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

**Pull request merged**
