### PR TITLE
[e2e] Stop creating Marketplace resources

### PR DESCRIPTION
**Pull request by aravindhp**
Now that we are managed by CVO, all the required Marketplace resources will be present in a cluster by default. This patch removes code that was creating these resources. Also removed downloading kubectl as that is not needed anymore.

### CODE REVIEW

**Comment by aravindhp** [comment]
@kevinrizza is `kubectl` required for the e2e tests? If not, I should remove installing that from `run-e2e-jobs.sh`.

**Comment by tkashem** [comment]
Question: My understanding of the pipeline is limited. So the installer deploys marketplace off of the image built from latest master branch. And the test should be pointing to a deployment off of an image built from the PR branch. For my clarity, where is this happening?

**Comment by aravindhp** [comment]
> Question: My understanding of the pipeline is limited. So the installer deploys marketplace off of the image built from latest master branch. And the test should be pointing to a deployment off of an image built from the PR branch. For my clarity, where is this happening?

The cluster used in the e2e uses a marketplace image that includes the bits from this PR and not from master. This is done as part of the CI pipeline.

**Pull request merged**
