### PR TITLE
OCPBUGS-5423: Run Default CatalogSource in Restricted mode

### PR DESCRIPTION
**Pull request by awgreene**
Problem: The marketplace operator has a dependency on an old version of the
operator-framework/api project, preventing it from setting newer fields on the
default catalogSources that it creates.

Solution: This PR updates the marketplace operator to use the latest version
of the operator-framework api, which required a kubernetes dependency
bump. These changes are being introduced so the marketplace-operator
is able to apply some of the latest changes introduced to the
catalogSource api.

This PR also updates the operator marketplace to use the new
coordination.k8s.io/leases api for leader election.

### CODE REVIEW

**Comment by awgreene** [comment]
Tested this on a 4.12 cluster using [these steps](https://docs.openshift.com/container-platform/4.11/authentication/understanding-and-managing-pod-security-admission.html#security-context-constraints-psa-alert-eval_understanding-and-managing-pod-security-admission):

```
$ oc adm must-gather -- /usr/bin/gather_audit_logs
$ zgrep -h pod-security.kubernetes.io/audit-violations must-gather.local.1016212489947876170/registry-build05-ci-openshift-org-ci-ln-w5vb982-stable-sha256-5b649183c0c550cdfd9f164a70c46f1e23b9e5a7e5af05fc6836bdd5280fbd79/audit_logs/kube-apiserver/*log.gz | jq -r 'select((.annotations["pod-security.kubernetes.io/audit-violations"] != null) and (.objectRef.resource=="pods")) | .objectRef.namespace + " " + .objectRef.name + " " + .objectRef.resource' | sort | uniq -c
   3 openshift-e2e-loki  pods

**Comment by grokspawn** [comment]
/lgtm
once the e2e passes

**Comment by grokspawn** [comment]
/hold
Waiting to see how the optional e2e goes

**Comment by grokspawn** [comment]
> > Waiting to see how the optional e2e goes
> 
> It hasn't been passing recently, AFAIR

You're right.  I see 1:3 pass:fail rate on this.  

/hold cancel

not barring merge with optional e2e

**Pull request merged**
