### PR TITLE
[docs] Remove marketplace-required-csv-annotations.md

### PR DESCRIPTION
**Pull request by awgreene**
- Update the Example CSV to specify that the value for the `metadata.annotations.certified` key should be a string

### CODE REVIEW

**Comment by aravindhp** [comment]
@awgreene we can deprecate this file and migrate it to [community-operators](https://github.com/operator-framework/community-operators/). We can delete it post code freeze from here.

**Comment by awgreene** [comment]
That sounds good to me @aravindhp

**Comment by awgreene** [comment]
This PR has been updated to remove the annotations document post code freeze.

[A new PR](https://github.com/operator-framework/community-operators/pull/19/) has been created to add the document to community-operators

**Pull request closed without merging**
