### PR TITLE
Update sdk to v0.3.0

### PR DESCRIPTION
**Pull request by SamiSousa**
- Update vendored dependencies to use sdk v0.3.0
- Updates controller-runtime to v0.1.8 for updated fakeclient
- Updates dependencies to use kubernetes 1.12.3

This allows us to use the controller-runtime's fakeclient in Marketplace unit tests.

Thanks @kevinrizza for your help with `dep`!

### CODE REVIEW

**Comment by SamiSousa** [comment]
@kevinrizza Seems that this is failing the e2e-aws-operator test; the build logs state the following error:
```
level=error msg="\t* aws_route53_zone.int: timeout while waiting for state to become 'INSYNC' (last state: 'PENDING', timeout: 15m0s)"
```
Am I okay to retrigger the failing test?

**Comment by tkashem** [comment]
> @kevinrizza Seems that this is failing the e2e-aws-operator test; the build logs state the following error:
> 
> ```
> level=error msg="\t* aws_route53_zone.int: timeout while waiting for state to become 'INSYNC' (last state: 'PENDING', timeout: 15m0s)"
> ```
> Am I okay to rerun the failing test?

I have seen this flake in my PR as well, I had to do a few retries before it got merged.

**Comment by SamiSousa** [comment]
@kevinrizza Addressed your comments, updated `SDK_VERSION` and `KUBE_VERSION` to match updates. Thanks for catching that!

**Pull request merged**
