### PR TITLE
OCPBUGS-17157: go.mod: bump operator-framework/api

### PR DESCRIPTION
**Pull request by stevekuznetsov**
The clients in this controller deserialize the CatalogSource objects that are defaulted, so the version of the API in the client libraries of this controller determines what fields exist in the objects that get created, regardless of what the server knows about.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Looks like the setting for community operators is too low, will fix later.

**Comment by jianzhangbjz** [comment]
It failed at `  Error: open /proc/8505/stat: no such file or directory: container process not found`, details in https://issues.redhat.com/browse/OCPBUGS-17157
/hold

**Pull request closed without merging**
