### PR TITLE
Bug 1737175: Do not hardcode GOOS/GOARCH

### PR DESCRIPTION
**Pull request by yselkowitz**
This change is required for building on other architectures.

### CODE REVIEW

**Comment by aravindhp** [comment]
/hold

This is duplicated by #225. Moreover this would need a BZ for it to be merged.
/cc @ecordell

**Comment by ecordell** [comment]
/hold cancel

Filed a BZ for this, and closing 225 in favor of this PR

**Comment by yselkowitz** [comment]
@ecordell thanks for unblocking this, what else is needed for approval and merge?

**Pull request merged**
