### PR TITLE
Update image tag to 4.15 for community operators

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
Update the image tag for the community operators index

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by everettraven — APPROVED** [review]

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by KeenonLee — COMMENTED** [review]
/retest

**Pull request merged**
