### PR TITLE
Update .gitignore to include Jetbrain IDEs

### PR DESCRIPTION
**Pull request by aravindhp**
Update .gitignore based on output from https://www.gitignore.io/api/go,vim,emacs,visualstudiocode,jetbrains

### CODE REVIEW

**Comment by awgreene** [comment]
@aravindhp Why does the `gitignore` file start with a newline?

**Comment by aravindhp** [comment]
> Why does the gitignore file start with a newline?

`.gitignore` was seeded by the SDK, so I am guessing it added the newline. Do you want me to remove it?

**Comment by awgreene** [comment]
> .gitignore was seeded by the SDK, so I am guessing it added the newline. Do you want me to remove it?
@aravindhp No need, I was just curious if it was by design.

**Pull request merged**
